#!/bin/bash

if [ -z "$2" ] ; then
    echo $(basename $0) JAIL SRC [SRC1 SRC2 ...] 
    exit 2
fi

if cp -n 2>&1 | grep -qE 'is non-portable|invalid option'; then
    CPN='--update=none'
else
    CPN='-n'
fi
CP="cp -av $CPN"

NAME=$1
if echo $NAME | grep -q '/' ; then
    TARGET=$NAME
else
    TARGET=/tmp/$NAME
fi
shift
mkdir -pv $TARGET

for SRC in $@ ; do
    if [ ! -e "$SRC" ] ; then
        echo "$SRC not found"
        exit 1
    fi
    if [ -d "$SRC" ] ; then
        if echo $SRC | grep -qE '^/' ; then
            D=$(dirname $SRC)
            D=${TARGET}${D}
            mkdir -pv $D 
            $CP $SRC ${D}/
        fi
        find $SRC -type f -executable | while read F ; do
            $0 $NAME $F
        done 
        find $SRC -name '*.so' | while read F ; do
            $0 $NAME $F
        done
        continue
    fi
    echo " --- $SRC"
    for L in $SRC $(ldd $SRC | sed -r 's/\(.+\)$//' | awk '/\//{print $NF}') ; do
        R=$(realpath $L)
        if [ "$R" = "$L" ] ; then
            unset R
        fi
        if [ -n "$R" ] ; then
            mkdir -pv ${TARGET}/$(dirname $R)
            $CP $R ${TARGET}/$(dirname $R)/
            mkdir -pv ${TARGET}/$(dirname $L)
            ln -sv $R ${TARGET}/$L 2>/dev/null
        else
            mkdir -p ${TARGET}/$(dirname $L)
            $CP $L ${TARGET}/$(dirname $L)/
        fi
    done
done

